### ISSUE TITLE
Implement file_mode

### ISSUE THREAD

**Issue by shaiksamad** [shaiksamad/diff-parser#3]
`file_mode` is a number at the end of the second line (insert line).

for example: 
`index 63ab03c..b5139e5 100644`

in the above index line `100644` is _file_mode_.

implement `file_mode` in `DiffBlock`

**Comment by Dongyeon1201** [comment]
The file mode written after the hash values, like index 63ab03c..b5139e5 100644, is applied only when modifying an existing file.

In cases where a file is newly created, deleted, or when file permissions are changed, such as with +x, the git log is recorded in a different format.

Therefore, we may need to either add a comment stating that the attribute file_mode is only used when ‘modifying an existing file,’ or manage it with various attribute names such as original/modified.

I’m curious about your thoughts, @shaiksamad

**[ Create File git log example ]**
```text
...
diff --git a/ttest.py b/ttest.py
new file mode 100644
index 0000000..a267c61
--- /dev/null
+++ b/ttest.py
...
```

**[ Delete File git log example ]**
```text
...
diff --git a/test3.py b/test3.py
deleted file mode 100644
index bdda917..0000000
--- a/test3.py
...
```

**Comment by shaiksamad** [comment]
if a line starts with `"index"` and either of the commit hash are not `"000000"` then last 6 digit is `file_mode`.

or

if a line starts with ( `"deleted file mode"` OR `"new file mode"` ) AND (`file_mode` is NULL) then the  last 6 digits of the line is the `file_mode`

I believe this will do the work.
